app = "nsr-hud-mody"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  NODE_ENV = "production"
  MEGA_BOT_DATA_DIR = "/data"

[experimental]
  auto_rollback = true

[vm]
  size = "shared-cpu-1x"
  memory = "256mb"

[[mounts]]
  source = "data"
  destination = "/data"
